### ISSUE TITLE
Volume applet bugs.

### ISSUE THREAD

**Issue by ghostplant** [rilian-la-te/vala-panel-extras#13] opened 2018-03-10 09:17 UTC
```sh
Scanning dependencies of target vala-panel-extras-volume
[ 33%] Building C object applets/volume/CMakeFiles/vala-panel-extras-volume.dir/volume.c.o
/home/admin/vala-panel-extras/applets/volume/volume.vala: In function ‘volume_icon_exporter_real_activate’:
/home/admin/vala-panel-extras/applets/volume/volume.vala:468:2: error: conversion to non-scalar type requested
         Gtk.Requisition requisition = Gtk.Requisition();
  ^
applets/volume/CMakeFiles/vala-panel-extras-volume.dir/build.make:70: recipe for target 'applets/volume/CMakeFiles/vala-panel-extras-volume.dir/volume.c.o' failed
make[2]: *** [applets/volume/CMakeFiles/vala-panel-extras-volume.dir/volume.c.o] Error 1
```

**Comment by ghostplant** [comment] 2018-03-10 09:29
Besides, I think it is better for vala-panel-extras-volume to beep according to the current desktop sound theme when altering the volume-bar, just like what mate-volume-applet from mate-media does.

**Comment by rilian-la-te** [comment] 2018-03-10 12:38
Will look for it. Can you attach a full log?

**Comment by rilian-la-te** [comment] 2018-03-10 12:46
Cannot reproduce it. Which versions of dependencies are you have (Vala, and libraries)?

It is best if you attach a full build log, not just place with error.

**Comment by ghostplant** [comment] 2018-03-10 12:48
the vala and all other libraries is installed from ubuntu 18.04, not other private added libraries.

**Comment by rilian-la-te** [comment] 2018-03-10 12:49
I do not know Ubuntu versions. I am on Arch) Please, full CMake log)

**Comment by rilian-la-te** [comment] 2018-03-10 12:54
And in Arch it builds fine. So, I definitely need a full log.

**Comment by ghostplant** [comment] 2018-03-10 17:25
Hi, changing the following line will fix the compile on Ubuntu 18.04:

```sh
-- Gtk.Requisition requisition = Gtk.Requisition();
++ Gtk.Requisition requisition = {0, 0};
```

**Comment by rilian-la-te** [comment] 2018-03-10 19:04
Will look for it.

**Comment by rilian-la-te** [comment] 2018-03-11 03:04
You can test and implement current GSound support. I do not know why it do not working on my machine.

**Comment by ghostplant** [comment] 2018-03-11 12:44
Build success while crash on execution:

warning: Unexpected size of section `.reg-xstate/19827' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./vala-panel-extras-volume'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg-xstate/19827' in core file.
#0  0x00007fcc98591f15 in ?? ()
[Current thread is 1 (Thread 0x7fcc86ffd700 (LWP 19827))]

**Comment by ghostplant** [comment] 2018-03-11 12:48
After fallback to commit `e6049cdcdfa72979e7146ff095fa86e493c54fa2`, the execution succeeded.

**Comment by rilian-la-te** [comment] 2018-03-11 13:30
Strange. On Arch all commit build fine. Do you have GSound installed?

**Comment by rilian-la-te** [comment] 2018-03-11 13:30
And run fine too

**Comment by ghostplant** [comment] 2018-03-11 13:34
libgsound is installed.

1) I found that the handler asound_set_volume() is expected to be the callback when altering volume not update_display(), so sound notification should be placed at asound_set_volume().
2) My ubuntu is using pulseaudio and it is compatible with alsa but not compatible with gsound. If you can find a way to place a notification using existing existing Alsa instead of adding GSound since the system might be not supported.

**Comment by ghostplant** [comment] 2018-03-11 13:37
I don't know how to play a sound by Alsa API. If it is known, placing the sound play code inside function asound_set_volume will fix the requirement. And I think gsound dependencies should be removed from this applet.

**Comment by rilian-la-te** [comment] 2018-03-11 13:42
If you want theme, it should use GSound.
update_display is also a callback. I will look for using Alsa in GSound or using libcanberra.

**Comment by rilian-la-te** [comment] 2018-03-11 13:43
Do you have libgsound-dev.

**Comment by ghostplant** [comment] 2018-03-11 13:43
Yes.

**Comment by ghostplant** [comment] 2018-03-11 13:45
It would be OK if user choose a default notification sound path such as `/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga`. I just don't like to extend more dependies and I think GSound doesn't work on all systems.

**Comment by ghostplant** [comment] 2018-03-11 13:46
```sh
from gi.repository import GSound

try:
    ctx = GSound.Context()
    ctx.init()
    ctx.play_simple({ GSound.ATTR_EVENT_ID : "audio-volume-change" })
except:
    # Handle errors
    pass
```
The python code above also crash on mu Ubuntu, so it seems libraries are installed but driver doesn't work with them well.

**Comment by ghostplant** [comment] 2018-03-11 13:48
Can you tell me how `Alsa` plays an oga file?

**Comment by ghostplant** [comment] 2018-03-11 14:00
From MATE volume applet, it plays with the sound by:

```sh
static gboolean
on_scale_button_release_event (GtkWidget      *widget,
                               GdkEventButton *event,
                               GvcChannelBar  *bar)
{
        ...
        ...

        /* Play a sound */
        ca_gtk_play_for_widget (GTK_WIDGET (bar), 0,
                                CA_PROP_EVENT_ID, "audio-volume-change",
                                CA_PROP_EVENT_DESCRIPTION, "Volume change",
                                CA_PROP_APPLICATION_ID, "org.mate.VolumeControl",
                                CA_PROP_APPLICATION_NAME, _("Volume Control"),
                                CA_PROP_APPLICATION_VERSION, VERSION,
                                CA_PROP_APPLICATION_ICON_NAME, "multimedia-volume-control",
                                NULL);
        return FALSE;
}
```

**Comment by ghostplant** [comment] 2018-03-11 14:53
Single-file Code-1:
```sh
using GSound;
public class HelloWorld {
	static void main () {
	var hello = new GSound.Context();
	hello.init();
        hello.play_simple(null,
		GSound.Attribute.EVENT_ID, "phone-incoming-call",
		GSound.Attribute.EVENT_DESCRIPTION, "hello world");
	Thread.usleep (2000000);
	}
}
```

Single-file Code 2:
```sh
using Canberra;

public class HelloWorld {
    static void main () {
        Context hello;
        Context.create(out hello);
        hello.play (0,
            PROP_EVENT_ID, "audio-volume-change",
            PROP_EVENT_DESCRIPTION, "audio-volume-change");
        Thread.usleep (2000000);
    }
}
```

Both of 2 codes above can be correct executed if I independently compile them by valac. But once the section code is added to the vala volume applets handlers, the applet will crash once executing these lines.

**Comment by ghostplant** [comment] 2018-03-11 15:04
```sh
#!/usr/bin/python3
import gi
gi.require_version('GSound', '1.0')
from gi.repository import GLib, GSound

hello = GSound.Context()
hello.init()
hello.play_simple({GSound.ATTR_EVENT_ID: "bell",
                   GSound.ATTR_EVENT_DESCRIPTION: "hello world"})
GLib.usleep(2000000)
```

I just found that gsound also support on my Ubuntu, and the reason why python3 crashes on gsound is due to a missing line `gi.require_version('GSound', '1.0')`. After adding it, the sound can be also played.

So I'm sure both gsound and libcanberra are supported on my Ubuntu but it have some conficts adding them into vala-panel-volume-applet.

Finally, I suggesting using libcanberra because all other MATE components are also using them while nobody uses libgsound so I perfer to reduce one extra dependencies.

**Comment by rilian-la-te** [comment] 2018-03-11 15:07
I want to use GSound, because it is not for MATE.
If you added libcanberra, it works?

**Comment by ghostplant** [comment] 2018-03-11 15:14
pavucontrol also uses libcanberra which is also an independent volume control tool. If you uses gsound, how you select an volume control tool that is not fat. `gnome-alsamixer` is too fat and it is gtk2-based which is too old.

**Comment by rilian-la-te** [comment] 2018-03-11 15:55
Libcanberra is OK (because gsound depends on it anyway). But you should do it properly.

**Comment by ghostplant** [comment] 2018-03-11 16:06
Recreating it will makes the applet crash on my system.

OK, i'll update it tomorrow to disable notification sound.

**Comment by rilian-la-te** [comment] 2018-03-11 17:13
Maybe I will merge and modify it myself.

**Comment by ghostplant** [comment] 2018-03-11 17:27
Ok, but i also wang to ensure whether oiginal sound notification is put in a wrong place. If so, extending any libs is unecessary.

**Comment by rilian-la-te** [comment] 2018-03-11 19:42
Now sound is played properly. Closing this.

**Closed** 2018-03-11 19:42 UTC
